// src/components/headlessui/Popup.tsx
import { Fragment } from "react";
import { Dialog, Transition } from "@headlessui/react";

type Props = React.PropsWithChildren<{
  show: boolean;
  darkBg?: boolean;
  handleClose: () => void;
}>;

const Popup = ({ show, darkBg, handleClose, children }: Props) => {
  return (
    <Transition show={show} as={Fragment}>
      <Dialog className="relative z-50" onClose={handleClose}>
        <Transition.Child
          className={`${
            darkBg ? `bg-opacity-90` : "bg-opacity-50"
          } fixed inset-0 bg-black`}
          enter="duration-300"
          enterFrom="opacity-0"
          enterTo="opacity-100"
          leave="duration-300"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
        ></Transition.Child>
        <Transition.Child
          className="fixed inset-0 overflow-y-auto overflow-x-hidden"
          enter="duration-300 delay-150"
          enterFrom="opacity-0 -translate-y-6"
          enterTo="opacity-100 transform-none"
          leave="duration-300"
          leaveFrom="opacity-100 transform-none"
          leaveTo="opacity-0 -translate-y-6"
        >
          <div className="flex min-h-full items-center justify-center">
            {children}
          </div>
        </Transition.Child>
      </Dialog>
    </Transition>
  );
};

export default Popup;

// src/components/headlessui/Popup.vue
<template>
  <TransitionRoot :show="show" as="template">
    <Dialog class="relative z-50" @close="$emit('close')">
      <TransitionChild
        class="fixed inset-0 bg-black"
        :class="darkBg ? `bg-opacity-90` : 'bg-opacity-50'"
        enter="duration-300"
        enter-from="opacity-0"
        enter-to="opacity-100"
        leave="duration-300"
        leave-from="opacity-100"
        leave-to="opacity-0"
      >
      </TransitionChild>
      <TransitionChild
        class="fixed inset-0 overflow-y-auto overflow-x-hidden"
        enter="duration-300 delay-150"
        enter-from="opacity-0 -translate-y-6"
        enter-to="opacity-100 transform-none"
        leave="duration-300"
        leave-from="opacity-100 transform-none"
        leave-to="opacity-0 -translate-y-6"
      >
        <div class="flex min-h-full items-center justify-center">
          <slot></slot>
        </div>
      </TransitionChild>
    </Dialog>
  </TransitionRoot>
</template>

<script setup lang="ts">
import { TransitionRoot, TransitionChild, Dialog } from "@headlessui/vue";

defineProps<{ show: boolean; darkBg?: boolean }>();
defineEmits<{ (event: "close"): void }>();
</script>
