// src/routes/o-nama/+page.svelte
<script lang="ts">
  import AlgebraGrupa from "./sections/AlgebraGrupa.svelte";
  import KakoDoNas from "./sections/KakoDoNas.svelte";
  import Povijest from "./sections/Povijest.svelte";
  import NaseVrijednosti from "./sections/NaseVrijednosti.svelte";
  import { onMount, type ComponentType } from "svelte";
  import { getImage } from "@/utils";

  const sectionsObserver = new IntersectionObserver((entries) => {
    entries.forEach(({ target, isIntersecting }) => {
      target.classList[isIntersecting ? "add" : "remove"]("section-visible");
    });
  });

  onMount(() => {
    document.querySelectorAll("section").forEach((section) => {
      sectionsObserver.observe(section);
    });
  });

  const sections: {
    component: ComponentType;
    id: string;
    title: string;
    icon: string;
    toggled?: boolean;
  }[] = [
    {
      component: NaseVrijednosti,
      id: "nase-vrijednosti",
      title: "Naše vrijednosti",
      icon: "flash_on",
    },
    {
      component: Povijest,
      id: "povijest",
      title: "Povijest",
      icon: "history",
    },
    {
      component: AlgebraGrupa,
      id: "algebra-grupa",
      title: "Algebra grupa",
      icon: "group",
    },
    {
      component: KakoDoNas,
      id: "kako-do-nas",
      title: "Kako do nas",
      icon: "explore",
    },
  ];
</script>

<main>
  <div class="main-img">
    <img
      class="w-full"
      src={getImage("kampus-iz-zraka-min-1.jpg")}
      alt="campus"
    />
  </div>
  <h1 class="main-title">O nama</h1>
  {#each sections as section (section.id)}
    <section id={section.id} class="transition duration-1000">
      <h2
        class="black-text-shadow relative py-8 text-center text-3xl font-semibold text-[var(--purple)] lg:bg-transparent"
        style:background-color={section.toggled ? "var(--purple-02)" : ""}
      >
        <button
          class="absolute inset-0 lg:hidden"
          on:click={() => (section.toggled = !section.toggled)}
        />
        <span class="material-icons align-middle text-3xl">
          {section.icon}
        </span>
        {section.title}
      </h2>
      <div class="lg:contents" class:hidden={!section.toggled}>
        <svelte:component this={section.component} />
      </div>
    </section>
  {/each}
</main>

// src/views/o-nama/ONama.tsx
import NaseVrijednosti from "@/views/o-nama/sections/NaseVrijednosti";
import Povijest from "@/views/o-nama/sections/Povijest";
import AlgebraGrupa from "@/views/o-nama/sections/AlgebraGrupa";
import KakoDoNas from "@/views/o-nama/sections/KakoDoNas";
import { useEffect, useState } from "react";
import { $image } from "@/main";

const sectionsObserver = new IntersectionObserver((entries) => {
  entries.forEach(({ target, isIntersecting }) => {
    target.classList[isIntersecting ? "add" : "remove"]("section-visible");
  });
});

interface Section {
  Component: () => JSX.Element;
  id: string;
  title: string;
  icon: string;
  toggled?: boolean;
}

const ONama = () => {
  useEffect(() => {
    document.querySelectorAll("section").forEach((section) => {
      sectionsObserver.observe(section);
    });
  }, []);

  const [sections, setSections] = useState<Section[]>([
    {
      Component: NaseVrijednosti,
      id: "nase-vrijednosti",
      title: "Naše vrijednosti",
      icon: "flash_on",
    },
    {
      Component: Povijest,
      id: "povijest",
      title: "Povijest",
      icon: "history",
    },
    {
      Component: AlgebraGrupa,
      id: "algebra-grupa",
      title: "Algebra grupa",
      icon: "group",
    },
    {
      Component: KakoDoNas,
      id: "kako-do-nas",
      title: "Kako do nas",
      icon: "explore",
    },
  ]);

  const toggleSection = (idx: number) => {
    const newSections = [...sections];
    newSections[idx].toggled = !newSections[idx].toggled;
    setSections(newSections);
  };

  return (
    <main>
      <div className="main-img">
        <img
          className="w-full"
          src={$image("kampus-iz-zraka-min-1.jpg")}
          alt="campus"
        />
      </div>
      <h1 className="main-title">O nama</h1>
      {sections.map(({ Component, id, title, icon, toggled }, i) => (
        <section id={id} className="transition duration-1000" key={id}>
          <h2
            className="black-text-shadow relative py-8 text-center text-3xl font-semibold text-[var(--purple)] lg:bg-transparent"
            style={{ backgroundColor: toggled ? "var(--purple-02)" : "" }}
          >
            <button
              className="absolute inset-0 lg:hidden"
              onClick={() => toggleSection(i)}
            ></button>
            <span className="material-icons align-middle text-3xl">{icon}</span>
            {title}
          </h2>
          <div className={`lg:block ${!toggled ? "hidden" : ""}`}>
            <Component />
          </div>
        </section>
      ))}
    </main>
  );
};

export default ONama;
