// src/views/Prijava.svelte
<script lang="ts">
  import { Navigate, navigateTo } from "svelte-router-spa";
  import { user } from "@/stores";
  import type { APICall, User } from "@/types";

  export let currentRoute;

  const isLogin = currentRoute.name == "/prijava";
  const form = { username: "", password: "" };
  const formAction =
    "https://www.fulek.com/data/api/user/" + (isLogin ? "login" : "register");
  let formResponse: APICall<User> = {
    isSuccess: false,
    errorMessages: [],
    statusCode: 0,
  };
  let isSubmitting = false;

  async function onSubmit() {
    isSubmitting = true;
    formResponse = await fetch(formAction, {
      method: "POST",
      body: JSON.stringify(form),
      headers: { "Content-Type": "application/json" },
    }).then((response) => response.json());
    if (!formResponse.isSuccess) {
      isSubmitting = false;
      return;
    }
    if (!formResponse.data) {
      isSubmitting = false;
      formResponse.isSuccess = false;
      return navigateTo("/prijava");
    }
    setTimeout(() => isLogin && navigateTo("/prijava"), 3000);
    user.signIn(formResponse.data);
  }
</script>

{#key isLogin + ""}
  <main class="m-auto w-full max-w-lg animate-reset p-3 opacity-0">
    <div class="mb-4 text-lg font-bold">
      {isLogin ? "PRIJAVA" : "REGISTRACIJA"} KORISNIKA
    </div>
    <form
      method="post"
      spellcheck="false"
      autocomplete="true"
      on:submit|preventDefault={onSubmit}
    >
      <div class="mb-3">
        <label for="username" class="mb-2 block text-sm font-bold text-gray-900"
          >Korisničko ime:</label
        >
        <input
          type="email"
          name="username"
          class="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 outline-none focus:border-blue-500"
          title="Ovo polje je obavezno!"
          placeholder="E-mail adresa..."
          on:invalid={function () {
            this.setCustomValidity("Neispravan email!");
          }}
          on:input={function () {
            this.setCustomValidity("");
          }}
          required
          bind:value={form.username}
        />
      </div>
      <div class="mb-3">
        <label for="password" class="mb-2 block text-sm font-bold text-gray-900"
          >Lozinka:</label
        >
        <input
          type="password"
          name="password"
          class="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 outline-none focus:border-blue-500"
          title="Ovo polje je obavezno!"
          on:invalid={function () {
            this.setCustomValidity("Ispunite ovo polje!");
          }}
          on:input={function () {
            this.setCustomValidity("");
          }}
          required
          bind:value={form.password}
        />
      </div>
      <button
        type="submit"
        class="mb-2 w-full rounded-md border-4 border-transparent bg-neutral-700 px-4 py-2 text-white transition-all duration-150 hover:bg-neutral-600 {isSubmitting
          ? '!border-neutral-300 !bg-white text-black'
          : ''}"
        disabled={isSubmitting}
      >
        {isLogin ? "Prijavi" : "Registriraj"} se
      </button>
      {#if formResponse.isSuccess}
        <div class="text-red-500">
          Uspješna prijava :) Na početnu stranicu za 3,2,1...
        </div>
      {/if}
      {#if formResponse.errorMessages.length}
        <div class="text-red-500">
          {@html formResponse.errorMessages.join("<br />")}
        </div>
      {/if}
      {#if isLogin}
        <div class="pt-3">
          Nemaš račun?
          <Navigate to="/registracija" styles="font-bold text-blue-500"
            >Registriraj se</Navigate
          >
        </div>
      {/if}
    </form>
  </main>
{/key}

// src/views/Prijava.tsx
import { useAppDispatch, signIn } from "@/store";
import { Link, useNavigate, useLocation } from "react-router-dom";
import type { APICall, User } from "@/types";
import { useState } from "react";

const Prijava = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const dispatch = useAppDispatch();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [form, setForm] = useState({ username: "", password: "" });
  const [formResponse, setFormResponse] = useState<APICall<User>>({
    isSuccess: false,
    errorMessages: [],
    statusCode: 0,
  });
  const isLogin = location.pathname == "/prijava";
  const formAction =
    "https://www.fulek.com/data/api/user/" + (isLogin ? "login" : "register");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    const response: APICall<User> = await fetch(formAction, {
      method: "POST",
      body: JSON.stringify(form),
      headers: { "Content-Type": "application/json" },
    }).then((response) => response.json());
    if (!response.isSuccess) {
      setFormResponse(response);
      return setIsSubmitting(false);
    }
    if (!response.data) {
      setFormResponse({ ...response, isSuccess: false });
      navigate("/prijava");
      return setIsSubmitting(false);
    }
    setFormResponse(response);
    setTimeout(() => isLogin && navigate("/"), 3000);
    dispatch(signIn(response.data));
  };

  return (
    <main
      className="m-auto w-full max-w-lg animate-reset p-3 opacity-0"
      key={isLogin + ""}
    >
      <div className="mb-4 text-lg font-bold">
        {isLogin ? "PRIJAVA" : "REGISTRACIJA"} KORISNIKA
      </div>
      <form
        method="post"
        spellCheck="false"
        autoComplete="true"
        onSubmit={handleSubmit}
      >
        <div className="mb-3">
          <label
            htmlFor="username"
            className="mb-2 block text-sm font-bold text-gray-900"
          >
            Korisničko ime:
          </label>
          <input
            type="email"
            name="username"
            className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 outline-none focus:border-blue-500"
            title="Ovo polje je obavezno!"
            placeholder="E-mail adresa..."
            onInvalid={(e) =>
              (e.target as HTMLInputElement).setCustomValidity(
                "Neispravan email!"
              )
            }
            onInput={(e) =>
              (e.target as HTMLInputElement).setCustomValidity("")
            }
            required
            onChange={(e) =>
              setForm({ ...form, username: e.target.value.trim() })
            }
          />
        </div>
        <div className="mb-3">
          <label
            htmlFor="password"
            className="mb-2 block text-sm font-bold text-gray-900"
          >
            Lozinka:
          </label>
          <input
            type="password"
            name="password"
            className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 outline-none focus:border-blue-500"
            title="Ovo polje je obavezno!"
            onInvalid={(e) =>
              (e.target as HTMLInputElement).setCustomValidity(
                "Ispunite ovo polje!"
              )
            }
            onInput={(e) =>
              (e.target as HTMLInputElement).setCustomValidity("")
            }
            required
            onChange={(e) => setForm({ ...form, password: e.target.value })}
          />
        </div>
        <button
          type="submit"
          className={`${
            isSubmitting ? " !border-neutral-300 !bg-white text-black" : ""
          } mb-2 w-full rounded-md border-4 border-transparent bg-neutral-700 px-4 py-2 text-white transition-all duration-150 hover:bg-neutral-600`}
          disabled={isSubmitting}
        >
          {isLogin ? "Prijavi" : "Registriraj"} se
        </button>
        {formResponse.isSuccess && (
          <div className="text-red-500">
            Uspješna prijava :) Na početnu stranicu za 3,2,1...
          </div>
        )}
        {!!formResponse.errorMessages.length && (
          <div
            className="text-red-500"
            dangerouslySetInnerHTML={{
              __html: formResponse.errorMessages.join("<br />"),
            }}
          ></div>
        )}
        {isLogin && (
          <div className="pt-3">
            Nemaš račun?&nbsp;
            <Link to="/registracija" className="font-bold text-blue-500">
              Registriraj se
            </Link>
          </div>
        )}
      </form>
    </main>
  );
};

export default Prijava;
