// src/components/HeaderLinks.svelte
<script lang="ts">
  import { Navigate } from "svelte-router-spa";
  import { isContactOpen } from "@/stores";

  export let isMobileView = false;
  export let handleClose = () => void 0;

  const links = [
    { href: "/", label: "Početna", icon: "home" },
    { href: "/o-nama", label: "O nama", icon: "insert_comment" },
    { href: "/novosti", label: "Novosti", icon: "info" },
    { href: "/nastavni-plan", label: "Nastavni plan", icon: "calendar_today" },
  ];
</script>

{#each links as { href, label, icon }}
  <Navigate to={href} styles="nav-btn">
    <button class="contents" on:click={handleClose}>
      <span class="material-icons pr-2" class:my-2={isMobileView}>{icon}</span>
      <span>{label}</span>
    </button>
  </Navigate>
{/each}
<button class="nav-btn w-full" on:click={() => isContactOpen.set(true)}>
  <span class="material-icons pr-2" class:my-2={isMobileView}> email </span>
  <span>Kontakt</span>
</button>

// src/components/HeaderLinks.tsx
import { NavLink } from "react-router-dom";
import { toggleContact, useAppDispatch } from "@/store";

const links = [
  { href: "/", label: "Početna", icon: "home" },
  { href: "/o-nama", label: "O nama", icon: "insert_comment" },
  { href: "/novosti", label: "Novosti", icon: "info" },
  { href: "/nastavni-plan", label: "Nastavni plan", icon: "calendar_today" },
];

type Props = { isMobileView?: boolean; handleClose?: () => void };

const HeaderLinks = ({ isMobileView, handleClose }: Props) => {
  const dispatch = useAppDispatch();
  return (
    <>
      {links.map(({ href, label, icon }) => (
        <NavLink
          key={href}
          to={href}
          className="nav-btn"
          onClick={() => isMobileView && handleClose && handleClose()}
        >
          <span className={`material-icons pr-2 ${isMobileView ? "my-2" : ""}`}>
            {icon}
          </span>
          <span>{label}</span>
        </NavLink>
      ))}
      <button
        className="nav-btn w-full"
        onClick={() => dispatch(toggleContact(true))}
      >
        <span className={`material-icons pr-2 ${isMobileView ? "my-2" : ""}`}>
          email
        </span>
        <span>Kontakt</span>
      </button>
    </>
  );
};

export default HeaderLinks;
