// src/components/headlessui/Modal.tsx
import { Dialog, Transition } from "@headlessui/react";
import { Fragment } from "react";

type Props = React.PropsWithChildren<{
  show: boolean;
  darkBg?: boolean;
  handleClose: () => void;
}>;

const Modal = ({ show, darkBg, handleClose, children }: Props) => {
  return (
    <Transition show={show} as={Fragment}>
      <Dialog className="relative z-50" onClose={handleClose}>
        <Transition.Child
          className={`${
            darkBg ? `bg-opacity-90` : "bg-opacity-50"
          } fixed inset-0 bg-black`}
          enter="duration-300"
          enterFrom="opacity-0"
          enterTo="opacity-100"
          leave="duration-300"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
        ></Transition.Child>
        <Transition.Child
          className="fixed inset-0 overflow-y-auto overflow-x-hidden"
          enter="duration-300 delay-150"
          enterFrom="opacity-0 -translate-y-6"
          enterTo="opacity-100 transform-none"
          leave="duration-300"
          leaveFrom="opacity-100 transform-none"
          leaveTo="opacity-0 -translate-y-6"
        >
          <div className="flex min-h-full items-center justify-center">
            {children}
          </div>
        </Transition.Child>
      </Dialog>
    </Transition>
  );
};

export default Modal;

// src/components/parts/Modal.svelte
<script lang="ts">
  import { cubicInOut } from "svelte/easing";
  import { fade } from "svelte/transition";

  export let show: boolean;
  export let darkBg = false;
  export let handleClose = () => void 0;

  // todo
  /* $: if (show) {
    document.body.style.overflow = "hidden";
  } else {
    document.body.style.overflow = "auto";
  } */

  function transitionSlot(node, { delay, duration }) {
    const opacity = +getComputedStyle(node).opacity;
    return {
      delay,
      duration,
      css: (t) => `
        opacity: ${t * opacity};
        transform: ${`translateY(-${1.5 * (1 - t)}rem)`};
        `,
      easing: cubicInOut,
    };
  }
</script>

{#if show}
  <div
    transition:fade={{ duration: 300 }}
    class="fixed inset-0 overflow-hidden z-50 bg-black {darkBg
      ? `bg-opacity-90`
      : 'bg-opacity-50'}"
  >
    <div
      in:transitionSlot={{ delay: 150, duration: 300 }}
      out:transitionSlot={{ delay: 0, duration: 300 }}
      aria-hidden="true"
      class="flex min-h-full items-center justify-center"
      on:click|self={handleClose}
    >
      <slot />
    </div>
  </div>
{/if}
