// src/App.tsx
import { Suspense, lazy, useState, useEffect } from "react";
import { Outlet } from "react-router-dom";
import { useAppSelector } from "./store";
import Header from "./components/Header";
import Footer from "./components/Footer";

const LazyContact = lazy(() => import("./components/Contact"));

const App = ({ notFound }: { notFound?: boolean }) => {
  const isContactOpen = useAppSelector((state) => state.isContactOpen);
  const [isContactLoaded, setIsContactLoaded] = useState(false);
  useEffect(() => {
    if (isContactOpen) setIsContactLoaded(true); // keeps the component alive to allow transitions
  }, [isContactOpen]);

  return (
    <>
      <Header />
      {notFound ? (
        <h1 className="grid flex-1 place-items-center text-xl">
          404 — Stranica ne postoji
        </h1>
      ) : (
        <Outlet />
      )}
      <Footer />
      <Suspense>{isContactLoaded && <LazyContact />}</Suspense>
    </>
  );
};

export default App;

// src/App.vue
<template>
  <Header />
  <RouterView />
  <Footer />
  <Contact v-if="isContactLoaded" />
</template>

<script setup lang="ts">
import { defineAsyncComponent, ref, watch } from "vue";
import { useStore } from "@/store";
import Header from "./components/Header.vue";
import Footer from "./components/Footer.vue";

const Contact = defineAsyncComponent(() => import("./components/Contact.vue"));
const store = useStore();
const isContactLoaded = ref(false); // keeps the component alive to allow transitions

watch(
  () => store.isContactOpen,
  () => (isContactLoaded.value = true)
);
</script>
